---
data: '2019-10-13_ciannovostroyki.csv'
locations: 'locations.csv'
data_path: data
max_square: 135
median_rooms: 2
mode_type_house: 'Монолитный'
sub_distance_left_border: 1400
sub_distance_right_border: 4500
start_date: '20190101'
fit_time_to_sub_params:
  - 8.78223984e+06
  - 3.26351157e-03
  - 4.69136386e+06
lat_center: 55.7522
lng_center: 37.6156
fit_inflation_params:
  - 2.95919954e+06
  - 1.00425360e+00